/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SampleFrame.java
 *
 * Created on 2011/05/26, 18:41:24
 */
package jp.navalvessel.demo;

import java.beans.PropertyVetoException;
import java.math.BigDecimal;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.tree.TreePath;

/**
 *
 * @author eguchi
 */
public class SampleFrame extends javax.swing.JFrame{

    /** Creates new form SampleFrame */
    public SampleFrame(){

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        mListValueField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        mSrcField = new javax.swing.JTextField();
        mCopyButton = new javax.swing.JButton();
        mDestField = new javax.swing.JTextField();
        mResetButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        mValue1Field = new javax.swing.JTextField();
        mOperatorComboBox = new javax.swing.JComboBox();
        mValue2Field = new javax.swing.JTextField();
        mEqualLabel = new javax.swing.JLabel();
        mAnswerField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mTreeValueField = new javax.swing.JTextField();
        mScrollPane2 = new javax.swing.JScrollPane();
        mTree = new javax.swing.JTree();
        mThreadPanel = new javax.swing.JPanel();
        mIncrementButton = new javax.swing.JButton();
        mValueLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("JList"));
        jPanel1.setName("jlistPanel"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jlist"); // NOI18N
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("selected:");

        mListValueField.setEditable(false);
        mListValueField.setName("selectedField"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mListValueField)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mListValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("JTextField"));
        jPanel2.setName("jtextFieldPanel"); // NOI18N

        mSrcField.setName("srcField"); // NOI18N

        mCopyButton.setText("copy>>");
        mCopyButton.setName("copyButton"); // NOI18N
        mCopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCopyButtonActionPerformed(evt);
            }
        });

        mDestField.setEditable(false);
        mDestField.setName("destField"); // NOI18N

        mResetButton.setText("reset");
        mResetButton.setName("resetButton"); // NOI18N
        mResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(mSrcField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mCopyButton)
                .addGap(18, 18, 18)
                .addComponent(mDestField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mResetButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(mSrcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mCopyButton)
                .addComponent(mDestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mResetButton))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mValue1Field.setName("value1"); // NOI18N
        mValue1Field.getDocument().addDocumentListener( calcHandler);

        mOperatorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-", "*", "/" }));
        mOperatorComboBox.setName("operator"); // NOI18N
        mOperatorComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mOperatorComboBoxItemStateChanged(evt);
            }
        });

        mValue2Field.setName("value2"); // NOI18N
        mValue2Field.getDocument().addDocumentListener( calcHandler);

        mEqualLabel.setText("=");

        mAnswerField.setEditable(false);
        mAnswerField.setName("answerField"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mValue1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mOperatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mValue2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mEqualLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mValue1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mOperatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mValue2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mEqualLabel)
                    .addComponent(mAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Jtree"));
        jPanel4.setName("jtreePanel"); // NOI18N

        jLabel3.setText("selected:");

        mTreeValueField.setEditable(false);
        mTreeValueField.setName("selectedField"); // NOI18N

        mTree.setName("jtree"); // NOI18N
        mTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                mTreeValueChanged(evt);
            }
        });
        mScrollPane2.setViewportView(mTree);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(mScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mTreeValueField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(mScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mTreeValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mThreadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("thread"));
        mThreadPanel.setName("threadPanel"); // NOI18N

        mIncrementButton.setText("increment after 5sec");
        mIncrementButton.setName("incrementButton"); // NOI18N
        mIncrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIncrementButtonActionPerformed(evt);
            }
        });

        mValueLabel.setText("1");
        mValueLabel.setName("value"); // NOI18N

        javax.swing.GroupLayout mThreadPanelLayout = new javax.swing.GroupLayout(mThreadPanel);
        mThreadPanel.setLayout(mThreadPanelLayout);
        mThreadPanelLayout.setHorizontalGroup(
            mThreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mThreadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mIncrementButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        mThreadPanelLayout.setVerticalGroup(
            mThreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mThreadPanelLayout.createSequentialGroup()
                .addGroup(mThreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mIncrementButton)
                    .addComponent(mValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mThreadPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mThreadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mIncrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIncrementButtonActionPerformed
        Runnable r = new Runnable(){

            @Override
            public void run(){
                try{
                    int value = Integer.parseInt( mValueLabel.getText() );
                    Thread.sleep( 5000 );
                    updateValue( value );
                } catch( InterruptedException ignore ){
                } catch( NumberFormatException ignore ){
                }
            }
        };
        Thread th = new Thread( r, "increment-value" );
        th.start();
        mIncrementButton.setEnabled( false );
    }//GEN-LAST:event_mIncrementButtonActionPerformed

    private void updateValue( final int value ){
        SwingUtilities.invokeLater( new Runnable(){
            @Override
            public void run(){
                mValueLabel.setText( Integer.toString( value + 1 ) );
                mIncrementButton.setEnabled( true );
            }
        } );
    }

    private void mCopyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCopyButtonActionPerformed
        String text = mSrcField.getText();
        mDestField.setText( text );
    }//GEN-LAST:event_mCopyButtonActionPerformed

    private void mResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mResetButtonActionPerformed
        mDestField.setText( "" );
    }//GEN-LAST:event_mResetButtonActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        Object value = jList1.getSelectedValue();
        mListValueField.setText( value == null ? "" : value.toString() );
    }//GEN-LAST:event_jList1ValueChanged

    private void mTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_mTreeValueChanged
        TreePath path = evt.getPath();
        String last = path.getLastPathComponent().toString();
        mTreeValueField.setText( last );
    }//GEN-LAST:event_mTreeValueChanged

    private void mOperatorComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mOperatorComboBoxItemStateChanged
        calc();
    }//GEN-LAST:event_mOperatorComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ){
        java.awt.EventQueue.invokeLater( new Runnable(){

            @Override
            public void run(){
                new SampleFrame().setVisible( true );
            }
        } );
    }

    private void calc(){
        try{
            BigDecimal value1 = new BigDecimal( mValue1Field.getText() );
            BigDecimal value2 = new BigDecimal( mValue2Field.getText() );
            String op = mOperatorComboBox.getSelectedItem().toString();
            BigDecimal ans = null;

            if( op.equals( "+" ) ){
                ans = value1.add( value2 );
            } else if( op.equals( "-" ) ){
                ans = value1.subtract( value2 );
            } else if( op.equals( "*" ) ){
                ans = value1.multiply( value2 );
            } else if( op.equals( "/" ) ){
                ans = value1.divide( value2 );
            }

            mAnswerField.setText( ans.toPlainString() );
        } catch( Exception e ){
            mAnswerField.setText( "error" );
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private DocumentListener calcHandler = new DocumentListener(){

        @Override
        public void changedUpdate( DocumentEvent e ){
            calc();
        }

        @Override
        public void insertUpdate( DocumentEvent e ){
            calc();
        }

        @Override
        public void removeUpdate( DocumentEvent e ){
            calc();
        }
    };
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mAnswerField;
    private javax.swing.JButton mCopyButton;
    private javax.swing.JTextField mDestField;
    private javax.swing.JLabel mEqualLabel;
    private javax.swing.JButton mIncrementButton;
    private javax.swing.JTextField mListValueField;
    private javax.swing.JComboBox mOperatorComboBox;
    private javax.swing.JButton mResetButton;
    private javax.swing.JScrollPane mScrollPane2;
    private javax.swing.JTextField mSrcField;
    private javax.swing.JPanel mThreadPanel;
    private javax.swing.JTree mTree;
    private javax.swing.JTextField mTreeValueField;
    private javax.swing.JTextField mValue1Field;
    private javax.swing.JTextField mValue2Field;
    private javax.swing.JLabel mValueLabel;
    // End of variables declaration//GEN-END:variables
}
